vaadin.launch-browser=true
spring.application.name=recipe-finder-backend
spring.main.allow-bean-definition-overriding=true

#DB Connection
spring.datasource.url=jdbc:mysql://localhost:3306/recipe_db?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#EDAMAN API
edamam.api.url=https://api.edamam.com/search
edamam.api.app-id=7280fca1
edamam.api.app-key=6b7812b1a2b7fa5072b1c458424b6245